ARG NODE_VERSION=18
ARG CLIENT_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY packages/client/package.json yarn.lock /app/
COPY packages/client/dist/ /app/dist
COPY packages/client/server /app/server

RUN yarn install --frozen-lockfile

CMD [ "node", "./server/index.js" ]
