ARG NODE_VERSION=18
ARG CLIENT_PORT=3000

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

EXPOSE $CLIENT_PORT

CMD [ "node", "./packages/client/server/index.js" ]