export const LANDING_PAGE_SECTIONS = [
  {
    className: 'landingPageSection1',
    title: 'Worm',
    text: 'Created by team 3',
    justify: 'end',
    align: 'end',
  },
  {
    className: 'landingPageSection2',
    title: 'About game',
    text: 'It’s basically a classic Snake but in the setting of Dune! Get your sandworm ready, because you are about to save Arrakis from Spice Harvesters.',
    justify: 'start',
    align: 'start',
    linkText: 'Start game',
    linkTo: '/',
  },
  {
    className: 'landingPageSection3',
    title: 'LeaderBoard',
    text: 'You can compare your results with friends and other players. Try hard if you want to be at the top!',
    justify: 'start',
    align: 'end',
    linkText: 'Go to leaderboard',
    linkTo: '/leaderboard',
  },
  {
    className: 'landingPageSection4',
    title: 'Forum',
    text: 'You can also start a thread in our forum page. Don’t be a stranger, talk to others and maybe get some insights about how to become the best at our game.',
    justify: 'start',
    align: 'start',
    linkText: 'Go to forum',
    linkTo: '/forum',
  },
]
